# Generated by Django 3.2.13 on 2022-07-02 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bellify_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitchChannel',
            fields=[
                ('channel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bellify_bot.channel')),
            ],
            options={
                'verbose_name': 'Twitch Channel',
                'verbose_name_plural': 'Twitch Channels',
            },
            bases=('bellify_bot.channel',),
        ),
        migrations.CreateModel(
            name='TwitchChannelUserItem',
            fields=[
                ('channeluseritem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bellify_bot.channeluseritem')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitch.twitchchannel')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=('bellify_bot.channeluseritem',),
        ),
        migrations.AddField(
            model_name='twitchchannel',
            name='users',
            field=models.ManyToManyField(through='twitch.TwitchChannelUserItem', to='bellify_bot.User'),
        ),
    ]
