# Generated by Django 4.0.6 on 2022-07-31 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitchchannel',
            name='is_live',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='twitchchannel',
            name='live_title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
