# Generated by Django 4.0.6 on 2022-07-19 12:56

from django.db import migrations, models
import twitch.models


class Migration(migrations.Migration):

    dependencies = [
        ('twitch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitchchannel',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to=twitch.models.twitch_thumbnail_directory_path),
        ),
    ]
