# Generated by Django 4.0.7 on 2022-08-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitchchannel',
            name='live_end_datetime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
