# Generated by Django 4.0.6 on 2022-08-10 13:56

import datetime
from django.db import migrations, models
from django.utils.timezone import now


class Migration(migrations.Migration):

    dependencies = [
        ('twitch', '0002_twitchchannel_is_live_twitchchannel_live_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitchchannel',
            name='live_end_datetime',
            field=models.DateTimeField(blank=True, default=now, null=True),
        ),
    ]
