# Generated by Django 4.0.6 on 2022-07-06 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitch', '0002_remove_twitchchannel_thumbnail_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitchchannel',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
