# Generated by Django 3.2.13 on 2022-07-04 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bellify_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeChannel',
            fields=[
                ('channel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bellify_bot.channel')),
                ('video_title', models.CharField(blank=True, max_length=256, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('old_video_title', models.CharField(blank=True, max_length=256, null=True)),
                ('old_video_url', models.URLField(blank=True, null=True)),
                ('live_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'YouTube Channel',
                'verbose_name_plural': 'YouTube Channels',
            },
            bases=('bellify_bot.channel',),
        ),
        migrations.CreateModel(
            name='YouTubeChannelUserItem',
            fields=[
                ('channeluseritem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bellify_bot.channeluseritem')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube.youtubechannel')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=('bellify_bot.channeluseritem',),
        ),
        migrations.AddField(
            model_name='youtubechannel',
            name='users',
            field=models.ManyToManyField(through='youtube.YouTubeChannelUserItem', to='bellify_bot.User'),
        ),
    ]
