# Generated by Django 4.0.6 on 2022-08-14 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubechannel',
            name='deleted_livestreams',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
