# Generated by Django 4.0.7 on 2022-08-20 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='youtubelivestream',
            old_name='is_new',
            new_name='is_notified',
        ),
        migrations.AddField(
            model_name='youtubelivestream',
            name='is_ended',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.DeleteModel(
            name='YouTubeEndedLivestream',
        ),
    ]
