# Generated by Django 3.2.13 on 2022-07-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubechannel',
            name='is_upcoming',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
