# Generated by Django 4.0.6 on 2022-07-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubechannel',
            name='is_saved_livestream',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='youtubechannel',
            name='iterations_skipped',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
