# Generated by Django 4.0.6 on 2022-07-29 13:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubechannel',
            name='saved_livestream_published',
            field=models.DateTimeField(blank=True, default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='youtubechannel',
            name='video_published',
            field=models.DateTimeField(blank=True, default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=utc), null=True),
        ),
    ]
