# Generated by Django 4.0.6 on 2022-07-09 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtubechannel',
            name='old_video_title',
        ),
        migrations.RemoveField(
            model_name='youtubechannel',
            name='old_video_url',
        ),
        migrations.AddField(
            model_name='youtubechannel',
            name='video_published',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
