# Generated by Django 4.0.7 on 2022-08-18 12:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeNotifiedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video_id', models.CharField(blank=True, max_length=20, null=True)),
                ('video_title', models.CharField(blank=True, max_length=256, null=True)),
                ('is_saved_livestream', models.BooleanField(blank=True, default=False, null=True)),
                ('iterations_skipped', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notified_videos', related_query_name='notified_video', to='youtube.youtubechannel')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Notified YouTube Video',
                'verbose_name_plural': 'Notified YouTube Videos',
            },
        ),
        migrations.RemoveField(
            model_name='youtubevideo',
            name='is_new',
        ),
        migrations.RemoveField(
            model_name='youtubevideo',
            name='iterations_skipped',
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='published_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='YouTubeDeletedVideo',
        ),
    ]
