# Generated by Django 4.0.6 on 2022-07-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtubechannel',
            name='is_saved_livestream',
        ),
        migrations.AddField(
            model_name='youtubechannel',
            name='saved_livestream_title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='youtubechannel',
            name='saved_livestream_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
