# Generated by Django 4.0.6 on 2022-08-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubedeletedvideo',
            name='is_counted_as_deleted_livestream',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
