# Generated by Django 4.0.6 on 2022-08-13 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='youtubevideo',
            old_name='is_notified',
            new_name='is_new',
        ),
    ]
