# Generated by Django 4.0.6 on 2022-07-31 14:24

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtubechannel',
            name='is_upcoming',
        ),
        migrations.RemoveField(
            model_name='youtubechannel',
            name='iterations_skipped',
        ),
        migrations.RemoveField(
            model_name='youtubechannel',
            name='live_url',
        ),
        migrations.RemoveField(
            model_name='youtubechannel',
            name='saved_livestream_published',
        ),
        migrations.RemoveField(
            model_name='youtubechannel',
            name='saved_livestream_title',
        ),
        migrations.RemoveField(
            model_name='youtubechannel',
            name='saved_livestream_url',
        ),
        migrations.RemoveField(
            model_name='youtubechannel',
            name='video_published',
        ),
        migrations.RemoveField(
            model_name='youtubechannel',
            name='video_title',
        ),
        migrations.RemoveField(
            model_name='youtubechannel',
            name='video_url',
        ),
        migrations.CreateModel(
            name='YouTubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video_id', models.CharField(blank=True, max_length=20, null=True)),
                ('video_title', models.CharField(blank=True, max_length=256, null=True)),
                ('video_published', models.DateTimeField(blank=True, default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=utc), null=True)),
                ('is_saved_livestream', models.BooleanField(blank=True, default=False, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', related_query_name='video', to='youtube.youtubechannel')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'YouTube Video',
                'verbose_name_plural': 'YouTube Videos',
            },
        ),
        migrations.CreateModel(
            name='YouTubeLivestream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('livestream_id', models.CharField(blank=True, max_length=20, null=True)),
                ('livestream_title', models.CharField(blank=True, max_length=256, null=True)),
                ('is_live', models.BooleanField(blank=True, default=False, null=True)),
                ('is_upcoming', models.BooleanField(blank=True, default=False, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livestreams', related_query_name='livestream', to='youtube.youtubechannel')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'YouTube Livestream',
                'verbose_name_plural': 'YouTube Livestreams',
            },
        ),
    ]
