# Generated by Django 4.0.6 on 2022-08-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_rename_is_notified_youtubevideo_is_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtubelivestream',
            name='is_notified',
        ),
        migrations.AddField(
            model_name='youtubelivestream',
            name='is_new',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='is_new',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
