# Generated by Django 4.0.7 on 2022-08-20 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_rename_is_new_youtubelivestream_is_notified_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='youtubevideo',
            old_name='published_datetime',
            new_name='published_at',
        ),
        migrations.RemoveField(
            model_name='youtubelivestream',
            name='is_ended',
        ),
        migrations.AddField(
            model_name='youtubelivestream',
            name='counted_as_deleted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='youtubelivestream',
            name='ended_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
