# Generated by Django 4.0.7 on 2022-08-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_remove_youtubelivestream_counted_as_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubelivestream',
            name='is_checked_for_deleted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
