# Generated by Django 4.0.7 on 2022-08-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_youtubenotifiedvideo_remove_youtubevideo_is_new_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideo',
            name='is_basic_notified',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='is_premium_notified',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='iterations_skipped',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.DeleteModel(
            name='YouTubeNotifiedVideo',
        ),
    ]
