# Generated by Django 4.0.6 on 2022-07-09 23:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_remove_youtubechannel_old_video_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubechannel',
            name='video_published',
            field=models.DateTimeField(blank=True, default=datetime.date(1, 1, 1), null=True),
        ),
    ]
