# Generated by Django 4.0.6 on 2022-07-28 11:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_remove_youtubechannel_is_saved_livestream_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubechannel',
            name='saved_livestream_published',
            field=models.DateTimeField(blank=True, default=datetime.date(1, 1, 1), null=True),
        ),
    ]
