# Generated by Django 4.0.6 on 2022-07-31 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_remove_youtubechannel_is_upcoming_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtubelivestream',
            name='is_live',
        ),
        migrations.RemoveField(
            model_name='youtubelivestream',
            name='is_upcoming',
        ),
    ]
