# Generated by Django 4.0.6 on 2022-08-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0003_remove_youtubelivestream_is_live_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideo',
            name='is_notified',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
