# Generated by Django 4.0.6 on 2022-08-01 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0004_youtubevideo_is_notified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtubevideo',
            name='video_published',
        ),
    ]
