# Generated by Django 4.0.6 on 2022-08-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0005_remove_youtubevideo_video_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideo',
            name='is_reuploaded',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
