# Generated by Django 4.0.6 on 2022-08-01 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('youtube', '0006_youtubevideo_is_reuploaded'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeDeletedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video_title', models.CharField(blank=True, max_length=256, null=True)),
                ('is_saved_livestream', models.BooleanField(blank=True, default=False, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deleted_videos', related_query_name='deleted_video', to='youtube.youtubechannel')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Deleted YouTube Video',
                'verbose_name_plural': 'Deleted YouTube Videos',
            },
        ),
    ]
