# Generated by Django 4.0.6 on 2022-08-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0007_youtubedeletedvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubedeletedvideo',
            name='video_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
