# Generated by Django 4.0.6 on 2022-08-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0008_youtubedeletedvideo_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubelivestream',
            name='is_notified',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
