# Generated by Django 4.0.6 on 2022-08-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0009_youtubelivestream_is_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubechannel',
            name='deleted_livestreams',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
