# Generated by Django 4.0.6 on 2022-08-05 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('youtube', '0010_youtubechannel_deleted_livestreams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtubechannel',
            name='deleted_livestreams',
        ),
        migrations.CreateModel(
            name='YouTubeEndedLivestream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('livestream_id', models.CharField(blank=True, max_length=20, null=True)),
                ('livestream_title', models.CharField(blank=True, max_length=256, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ended_livestreams', related_query_name='ended_livestream', to='youtube.youtubechannel')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Ended Livestream',
                'verbose_name_plural': 'Ended Livestreams',
            },
        ),
    ]
