# Generated by Django 4.0.6 on 2022-08-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0011_remove_youtubechannel_deleted_livestreams_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='youtubeendedlivestream',
            options={'verbose_name': 'Ended YouTube Livestream', 'verbose_name_plural': 'Ended YouTube Livestreams'},
        ),
        migrations.AddField(
            model_name='youtubechannel',
            name='deleted_livestreams',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='iterations_skipped',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
