# Generated by Django 4.0.6 on 2022-07-06 20:28

from django.db import migrations, models
import django.db.models.deletion
from django.contrib.auth import get_user_model


def create_initial_superuser(apps, schema_editor):
    User = get_user_model()
    User.objects.create_superuser(
        'admin', 'admin@admin.com', 'admin')


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_at', models.DateTimeField(
                    auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.PositiveBigIntegerField(
                    primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=64, null=True)),
                ('first_name', models.CharField(
                    blank=True, max_length=256, null=True)),
                ('last_name', models.CharField(
                    blank=True, max_length=256, null=True)),
                ('deep_link', models.CharField(blank=True, max_length=64, null=True)),
                ('menu', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[
                 ('B', 'Basic'), ('P', 'Premium')], default='B', max_length=1)),
                ('language', models.CharField(blank=True, choices=[('en', 'English'), ('ru', 'Russian'), (
                    'ua', 'Ukrainian')], default=None, help_text="Telegram client's language", max_length=2, null=True)),
                ('max_youtube_channels_number', models.PositiveIntegerField(
                    blank=True, default=5, null=True, verbose_name='YouTube Quota')),
                ('max_twitch_channels_number', models.PositiveIntegerField(
                    blank=True, default=0, null=True, verbose_name='Twitch Quota')),
                ('is_tutorial_finished', models.BooleanField(default=False)),
                ('is_blocked_bot', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE,
                 related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Telegram User',
                'verbose_name_plural': 'Telegram Users',
            },
        ),
        migrations.CreateModel(
            name='ChannelUserItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(
                    auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel_title', models.CharField(
                    blank=True, default='', max_length=128, null=True)),
                ('is_muted', models.BooleanField(default=False)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE,
                 related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='bellify_bot.user')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(
                    auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel_id', models.CharField(max_length=128, unique=True)),
                ('channel_url', models.URLField(unique=True)),
                ('channel_title', models.CharField(max_length=128)),
                ('live_title', models.CharField(
                    blank=True, max_length=256, null=True)),
                ('is_live', models.BooleanField(
                    blank=True, default=False, null=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE,
                 related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.RunPython(create_initial_superuser)
    ]
