# Generated by Django 3.2.13 on 2022-07-05 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bellify_bot', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
