# Generated by Django 4.0.6 on 2022-07-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bellify_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_icons_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
