# Generated by Django 4.0.6 on 2022-07-31 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bellify_bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='is_live',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='live_title',
        ),
    ]
