# Generated by Django 4.0.7 on 2022-08-15 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bellify_bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='channel_url',
        ),
    ]
