# Generated by Django 4.0.6 on 2022-07-12 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bellify_bot', '0002_user_is_icons_disabled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_icons_disabled',
            new_name='is_manage_icons_disabled',
        ),
        migrations.AddField(
            model_name='user',
            name='is_message_icons_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
