# Generated by Django 4.0.7 on 2022-08-15 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bellify_bot', '0003_alter_channeluseritem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channeluseritem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bellify_bot.user'),
        ),
    ]
